CREATE TABLE comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    post_id     BIGINT      NOT NULL REFERENCES posts(id),
    author_id   BIGINT      NOT NULL REFERENCES users(id),

    body        VARCHAR(500) NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_comments_post
    ON comments(post_id);

CREATE INDEX idx_comments_author
    ON comments(author_id);

CREATE INDEX idx_comments_created
    ON comments(created_at);
    