-- reports: 投稿・コメントへの通報（target_type で対象を区別）
CREATE TABLE reports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id  BIGINT      NOT NULL REFERENCES users(id),  -- 通報した人（管理者のみ可視）
    target_type  VARCHAR(10) NOT NULL,                       -- POST / COMMENT
    target_id    BIGINT      NOT NULL,                       -- 投稿id または コメントid
    reason       VARCHAR(500),                               -- 理由（自由記述・任意）
    status       VARCHAR(10) NOT NULL DEFAULT 'PENDING',     -- PENDING / RESOLVED
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 同じ人が同じ対象を重複通報できないように（1人1対象1回）
CREATE UNIQUE INDEX uq_reports_reporter_target
    ON reports(reporter_id, target_type, target_id);

-- 管理者が未対応の通報を新しい順に見る用
CREATE INDEX idx_reports_status_created ON reports(status, created_at);