-- notifications: いいね・返信の受信通知（フォローは通知しない）
CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT      NOT NULL REFERENCES users(id),  -- 受け取る人
    actor_id     BIGINT      NOT NULL REFERENCES users(id),  -- 操作した人
    post_id      BIGINT      NOT NULL REFERENCES posts(id),  -- 対象の投稿/返信
    type         VARCHAR(20) NOT NULL,                       -- LIKE / REPLY
    is_read      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, is_read, created_at);
