-- users: 認証情報・ロール・状態・公開ハンドル・自己紹介
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle          VARCHAR(50)  NOT NULL UNIQUE,            -- 公開用の不透明ハンドル
    employee_no     VARCHAR(50)  NOT NULL UNIQUE,            -- 社員番号
    email           VARCHAR(255) NOT NULL UNIQUE,            -- @skywill.jp のみ（検証はアプリ側）
    password        VARCHAR(255) NOT NULL,                   -- 開発段階は平文 / ハッシュ化は後で
    role            VARCHAR(20)  NOT NULL DEFAULT 'USER',    -- USER / ADMIN
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE / DISABLED
    email_verified  BOOLEAN      NOT NULL DEFAULT TRUE,      -- フェーズ3のメール本人確認用に予約
    bio             VARCHAR(200),                            -- 自己紹介（200字以内）
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
