-- tags: 投稿タグ・興味タグ・フォロー可能トピックの共通語彙
CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,   -- 小文字化・トリムで正規化（アプリ側）
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
