-- posts: 投稿と返信を1テーブルで管理（parent_id が NULL=投稿 / 値あり=返信）
CREATE TABLE posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   BIGINT       NOT NULL REFERENCES users(id),
    parent_id   BIGINT       REFERENCES posts(id),           -- 自己参照（返信のとき親投稿）
    body        VARCHAR(1000) NOT NULL,                      -- 本文（1000字以内）
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,         -- 論理削除フラグ
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_posts_author    ON posts(author_id);
CREATE INDEX idx_posts_parent    ON posts(parent_id);
CREATE INDEX idx_posts_created   ON posts(created_at);
