-- user_tags: プロフィールの興味タグ（category で 技術/趣味/資格 を区別）
CREATE TABLE user_tags (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL REFERENCES users(id),
    tag_id   BIGINT      NOT NULL REFERENCES tags(id),
    category VARCHAR(20) NOT NULL,                 -- TECH / HOBBY / CERT
    CONSTRAINT uq_user_tags UNIQUE (user_id, tag_id, category)
);
CREATE INDEX idx_user_tags_tag ON user_tags(tag_id);
