-- post_tags: 投稿へのタグ付け
CREATE TABLE post_tags (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id),
    tag_id  BIGINT NOT NULL REFERENCES tags(id),
    CONSTRAINT uq_post_tags UNIQUE (post_id, tag_id)
);
CREATE INDEX idx_post_tags_tag ON post_tags(tag_id);
