-- follows: 人のフォロー関係（nickname は付与者のみ可視・相手に非通知）
CREATE TABLE follows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT       NOT NULL REFERENCES users(id),  -- フォローする側
    followee_id BIGINT       NOT NULL REFERENCES users(id),  -- される側
    nickname    VARCHAR(50),                                 -- NULL可
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_follows UNIQUE (follower_id, followee_id)
);
CREATE INDEX idx_follows_followee ON follows(followee_id);
