-- tag_follows: タグ（トピック）のフォロー
CREATE TABLE tag_follows (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    tag_id     BIGINT      NOT NULL REFERENCES tags(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tag_follows UNIQUE (user_id, tag_id)
);
CREATE INDEX idx_tag_follows_tag ON tag_follows(tag_id);
