-- likes: 投稿/返信へのいいね（1人1いいね）
CREATE TABLE likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    post_id    BIGINT      NOT NULL REFERENCES posts(id),    -- 投稿/返信どちらも posts
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_likes UNIQUE (user_id, post_id)
);
CREATE INDEX idx_likes_post ON likes(post_id);
