-- view_logs: 閲覧履歴（レコメンド入力・監査用、非公開・全閲覧を記録）
CREATE TABLE view_logs (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT      NOT NULL REFERENCES users(id),
    post_id   BIGINT      NOT NULL REFERENCES posts(id),
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_view_logs_user ON view_logs(user_id, viewed_at);
CREATE INDEX idx_view_logs_post ON view_logs(post_id);
